### ISSUE TITLE
CSVReader and JSONReader not compatible with Garg

### ISSUE THREAD

**Issue by kmdouglass** [kmdouglass/bstore#81]
The new CSVReader and JSONReader objects are currently not compatible with [Garg](https://github.com/kmdouglass/garg) the tool that I created for the purpose of easily assigning values to function arguments via a GUI. This is because Garg does not support parameters that are `POSITIONAL_ONLY`, yet CSVReader and JSONReader have a self-defined `POSITIONAL_ONLY` parameter called `filename`.

```python
In [11]: c = garg.Garg(readers.CSVReader()); c.run()
Unexpected error: <class 'KeyError'>
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/douglass/anaconda3/envs/bstore/lib/python3.5/tkinter/__init__.py", line 1550, in __call__
    return self.func(*args)
  File "/home/douglass/anaconda3/envs/bstore/lib/python3.5/site-packages/garg.py", line 114, in on_ok_button
    args = self.get_arguments()
  File "/home/douglass/anaconda3/envs/bstore/lib/python3.5/site-packages/garg.py", line 82, in get_arguments
    params[param.name] = literal_eval(view_params[param.name])
KeyError: 'filename'

```

**Comment by kmdouglass** [comment]
This is actually a problem with Garg. It will be fixed there instead.
